[package]
name = "maa-framework"
description = "Rust bindings for MaaFramework"
version = "0.3.1"
edition = "2021"
license = "LGPL-3.0"
homepage = "https://github.com/MaaAssistantArknights/MaaFramework"
repository = "https://github.com/MaaAssistantArknights/MaaFramework"
readme = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_with = "3.7.0"
thiserror = "^1.0"

[build-dependencies]
bindgen = "0.69.4"
ureq = "2.9.6"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }

[features]
default = ["toolkit", "adb", "win32", "dbg", "custom", "internal"]
toolkit = []
adb = []
win32 = []
dbg = []
custom = [
    "custom_recognizer",
    "custom_controller",
    "custom_action",
    "sync_context",
]
custom_recognizer = ["sync_context"]
custom_controller = ["sync_context"]
custom_action = ["sync_context"]
sync_context = []
internal = []
download = []
