name: Build and Deploy Docs
on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build Docs
        run: |
          cargo doc --no-deps --features download
          cp -r target/doc ./
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v2
        with:
          path: doc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Doc
        uses: actions/deploy-pages@v4
        id: deployment