name: Build and Deploy Docs
on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build Docs
        run: |
          cargo doc --no-deps --features download
          cp -r target/doc ./
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./doc